app/views.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, flash
from datetime import datetime

views_bp = Blueprint('views', __name__)
from app.models import db, User, Restaurant, RestaurantComment, Reservation, Table

from flask_login import login_user, login_manager, login_required, logout_user, current_user
login_manager.login_view = 'login'


@views_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        data = request.form
        email = data['email']
        password = data['password']
        existing_user = User.query.filter_by(email=email).first()
        if not existing_user:
            return render_template('login.html', message='Invalid login. Please check your email and password.')

        if existing_user.password == password:
            login_user(existing_user)
            return redirect('/main')
        else:
            print("invalid")
            return render_template('login.html', message='Invalid login. Please check your username and password.')
    else:
        return render_template('login.html')


@views_bp.route('/', methods=['GET', 'POST'])
def home():
    return render_template('home.html')


@views_bp.route('/profile')
@login_required
def profile():
    return render_template('profile.html', current_user=current_user)


@views_bp.route('/add_comment/<int:restaurant_id>', methods=['POST'])
@login_required
def add_comment(restaurant_id):
    restaurant = Restaurant.query.get_or_404(restaurant_id)

    comment_text = request.form.get('comment_text')
    rating = int(request.form.get('rating'))

    # Создание нового комментария
    new_comment = RestaurantComment(
        user=current_user,
        restaurant=restaurant,
        comment_text=comment_text,
        rating=rating
    )

    db.session.add(new_comment)
    db.session.commit()

    flash('Comment added successfully!', 'success')
    return redirect(url_for('views.view_restaurant', restaurant_id=restaurant.restaurant_id))


@views_bp.route('/cancel_reservation/<int:reservation_id>', methods=['POST'])
@login_required
def cancel_reservation(reservation_id):
    reservation = Reservation.query.get_or_404(reservation_id)

    if current_user.user_id != reservation.user_id:
        return redirect(url_for('views.profile'))

    canceled_table = reservation.table
    canceled_table.is_booked = False

    db.session.delete(reservation)
    db.session.commit()

    return redirect(url_for('views.profile'))


@views_bp.route('/restaurant/<restaurant_id>')
@login_required
def view_restaurant(restaurant_id):
    restaurant = Restaurant.query.get(restaurant_id)
    return render_template('restaurant.html', restaurant=restaurant)


@views_bp.route('/logout', methods=['POST'])
@login_required
def logout():
    logout_user()

    return redirect(url_for('views.home'))


@views_bp.route('/booking')
@login_required
def booking():
    restaurants = Restaurant.query.all()
    return render_template('booking.html', restaurants=restaurants)


@views_bp.route('/main')
@login_required
def main_page():
    return render_template('main.html')


@views_bp.route('/signup', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
        existing_user_username = User.query.filter_by(username=username).first()
        if existing_user_username:
            return render_template('signup.html', message='User already exists')
        else:
            new_user = User(username=username, email=email, password=password)

            db.session.add(new_user)
            db.session.commit()
            # Successful login
            return redirect("/login")
    else:
        return render_template('signup.html')



@views_bp.route('/booking/<int:restaurant_id>/<int:table_id>', methods=['GET', 'POST'])
@login_required
def book_table(restaurant_id, table_id):
    if request.method == 'POST':
        date = request.form.get('date')


        reservation = Reservation(
            user_id=current_user.id,
            table_id=table_id,
            reservation_time=date
        )

        db.session.add(reservation)
        db.session.commit()

        return redirect(url_for('views.booking_success'))

    table = Table.query.get(table_id)

    return render_template('booking.html', restaurant_id=restaurant_id, table_id=table_id, table=table)


@views_bp.route('/select_time/<int:restaurant_id>', methods=['GET'])
@login_required
def select_time(restaurant_id):
    selected_table_id = int(request.args.get('table'))
    selected_table_number = next(
        (table.table_number for table in Table.query.filter_by(table_id=selected_table_id, is_booked=False)), None)
    return render_template('select_time.html', restaurant=Restaurant.query.get_or_404(restaurant_id),
                           restaurant_id=restaurant_id, selected_table_id=selected_table_id,
                           selected_table_number=selected_table_number)


@views_bp.route('/confirm_booking/<int:restaurant_id>/<int:table_id>', methods=['POST'])
@login_required
def confirm_booking(restaurant_id, table_id):
    selected_date = request.form.get('date')
    selected_time = request.form.get('time')

    booked_table = Table.query.get_or_404(table_id)

    new_reservation = Reservation(user=current_user, table=booked_table,
                                  reservation_time=datetime.strptime(f"{selected_date} {selected_time}",
                                                                     "%Y-%m-%d %H:%M"))

    db.session.add(new_reservation)
    db.session.commit()

    booked_table.is_booked = True
    db.session.commit()

    return redirect(url_for('views.view_restaurant', restaurant_id=restaurant_id))

app/templates/booking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurants Booking</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');

        body {
            background: #1abc9c;
            font-family: 'Poppins', sans-serif;
            overflow: hidden;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        h1 {
            color: #fff;
            text-align: center;
            margin-bottom: 20px;
        }

        ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
            max-height: 400px; /* Ограничение высоты для скролла */
            overflow-y: auto; /* Включение вертикального скролла при превышении высоты */
            text-align: center;
        }

        li {
            background: #fff;
            border-radius: 5px;
            box-shadow: 0px 4px 10px 1px rgba(0, 0, 0, 0.1);
            margin: 10px;
            padding: 20px;
            width: 300px;
        }

        h2 {
            color: #16a085;
            font-size: 24px;
            margin-bottom: 10px;
        }

        h3 {
            color: #333;
            font-size: 18px;
            margin-bottom: 15px;
        }

        p {
            color: #777;
            font-size: 14px;
            margin-bottom: 10px;
        }

        a {
            text-decoration: none;
            background: #16a085;
            color: #fff;
            padding: 8px 16px;
            border-radius: 5px;
            font-weight: bold;
            transition: background 0.3s ease;
        }

        a:hover {
            background: #12876f;
        }
    </style>
</head>
<body>

<h1>Choose a Place for Booking</h1>

<ul>
    {% for restaurant in restaurants %}
        <li>
            <h2>{{ restaurant.name }}</h2>
            <p>{{ restaurant.address }}</p>
            <h3>{{ restaurant.description }}</h3>
            <a href="{{ url_for('views.view_restaurant', restaurant_id=restaurant.restaurant_id) }}">Book a Table</a>
        </li>
    {% endfor %}
</ul>

</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home | CodingLab</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }

        body {
            background: #1abc9c;
            overflow: hidden;
        }

        ::selection {
            background: rgba(26, 188, 156, 0.3);
        }

        .container {
            max-width: 440px;
            padding: 0 20px;
            margin: 170px auto;
        }

        .wrapper {
            width: 100%;
            background: #fff;
            border-radius: 5px;
            box-shadow: 0px 4px 10px 1px rgba(0, 0, 0, 0.1);
        }

        .wrapper .title {
            height: 90px;
            background: #16a085;
            border-radius: 5px 5px 0 0;
            color: #fff;
            font-size: 30px;
            font-weight: 600;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .wrapper form {
            padding: 30px 25px 25px 25px;
        }

        .wrapper form .row {
            height: 45px;
            margin-bottom: 15px;
            position: relative;
        }

        .wrapper form .row input {
            height: 100%;
            width: 100%;
            outline: none;
            padding-left: 60px;
            border-radius: 5px;
            border: 1px solid lightgrey;
            font-size: 16px;
            transition: all 0.3s ease;
        }

        form .row input:focus {
            border-color: #16a085;
            box-shadow: inset 0px 0px 2px 2px rgba(26, 188, 156, 0.25);
        }

        form .row input::placeholder {
            color: #999;
        }

        .wrapper form .row i {
            position: absolute;
            width: 47px;
            height: 100%;
            color: #fff;
            font-size: 18px;
            background: #16a085;
            border: 1px solid #16a085;
            border-radius: 5px 0 0 5px;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .wrapper form .pass {
            margin: -8px 0 20px 0;
        }

        .wrapper form .pass a {
            color: #16a085;
            font-size: 17px;
            text-decoration: none;
        }

        .wrapper form .pass a:hover {
            text-decoration: underline;
        }

        .wrapper form .button input {
            color: #fff;
            font-size: 20px;
            font-weight: 500;
            padding-left: 0px;
            background: #16a085;
            border: 1px solid #16a085;
            cursor: pointer;
        }

        form .button input:hover {
            background: #12876f;
        }

        .home-button {
            display: block;
            width: 100%;
            padding: 15px;
            background-color: #16a085;
            color: #fff;
            text-align: center;
            text-decoration: none;
            font-size: 18px;
            transition: background-color 0.3s ease;
        }

        .wrapper form .signup-link {
            text-align: center;
            margin-top: 20px;
            font-size: 17px;
        }

        .wrapper form .signup-link a {
            color: #16a085;
            text-decoration: none;
        }

        form .signup-link a:hover {
            text-decoration: underline;
        }

        .home-button:hover {
            background-color: #12876f;
        }

    </style>
</head>
<body>


<div class="container">
    <div class="wrapper">
        <div class="title"><span>Home</span></div>
        <div class="button-container">
            <a href="{{ url_for('views.login') }}" class="home-button">Login</a>
        </div>
    </div>
</div>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<!-- Created By CodingLab - www.codinglabweb.com -->
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form | CodingLab</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Poppins', sans-serif;
        }

        body {
            background: #1abc9c;
            overflow: hidden;
        }

        ::selection {
            background: rgba(26, 188, 156, 0.3);
        }

        .container {
            max-width: 440px;
            padding: 0 20px;
            margin: 170px auto;
        }

        .wrapper {
            width: 100%;
            background: #fff;
            border-radius: 5px;
            box-shadow: 0px 4px 10px 1px rgba(0, 0, 0, 0.1);
        }

        .wrapper .title {
            height: 90px;
            background: #16a085;
            border-radius: 5px 5px 0 0;
            color: #fff;
            font-size: 30px;
            font-weight: 600;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .wrapper form {
            padding: 30px 25px 25px 25px;
        }

        .wrapper form .row {
            height: 45px;
            margin-bottom: 15px;
            position: relative;
        }

        .wrapper form .row input {
            height: 100%;
            width: 100%;
            outline: none;
            padding-left: 60px;
            border-radius: 5px;
            border: 1px solid lightgrey;
            font-size: 16px;
            transition: all 0.3s ease;
        }

        form .row input:focus {
            border-color: #16a085;
            box-shadow: inset 0px 0px 2px 2px rgba(26, 188, 156, 0.25);
        }

        form .row input::placeholder {
            color: #999;
        }

        .wrapper form .row i {
            position: absolute;
            width: 47px;
            height: 100%;
            color: #fff;
            font-size: 18px;
            background: #16a085;
            border: 1px solid #16a085;
            border-radius: 5px 0 0 5px;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .wrapper form .pass {
            margin: -8px 0 20px 0;
        }

        .wrapper form .pass a {
            color: #16a085;
            font-size: 17px;
            text-decoration: none;
        }

        .wrapper form .pass a:hover {
            text-decoration: underline;
        }

        .wrapper form .button input {
            color: #fff;
            font-size: 20px;
            font-weight: 500;
            padding-left: 0px;
            background: #16a085;
            border: 1px solid #16a085;
            cursor: pointer;
        }

        form .button input:hover {
            background: #12876f;
        }

        .wrapper form .signup-link {
            text-align: center;
            margin-top: 20px;
            font-size: 17px;
        }

        .wrapper form .signup-link a {
            color: #16a085;
            text-decoration: none;
        }

        form .signup-link a:hover {
            text-decoration: underline;
        }

    </style>
</head>
<body>


<div class="container">
    <div class="wrapper">
        <div class="title"><span>Login Form</span></div>
        <!-- Додані атрибути method та id -->
        <form action="/login" method="post" id="loginForm">
            <div class="row">
                <i class="fas fa-user"></i>
                <!-- Додано атрибут name -->
                <input type="text" name="email" placeholder="Email" required>
            </div>
            <div class="row">
                <i class="fas fa-lock"></i>
                <!-- Додано атрибут name -->
                <input type="password" name="password" placeholder="Password" required>
            </div>
            <div class="row button">
                <input type="submit" value="Login">
            </div>
            <div class="signup-link">Not a member? <a href="/signup">Signup now</a></div>
            <div class="signup-link">{{ message }}</div>
        </form>
    </div>
</div>
</body>
</html>

app/templates/main.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Page</title>
    <style>
        .button-container {
            display: flex;
            justify-content: space-between;
        }

        .main-button {
            width: 45%;
            flex-grow: 1;
            height: 600px;
            padding: 20px;
            background-color: #16a085; /* Change this color to the desired one */
            color: #fff;
            text-align: center;
            text-decoration: none;
            font-size: 100px;
            border-radius: 15px;
            margin: 0 5px; /* Adjust the margin between buttons */
            transition: background-color 0.3s ease;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .main-button:hover {
            background-color: #12876f; /* Change this color to the desired hover color */
        }

        body {
            background: #1abc9c;
            overflow: hidden;
        }

        .fa-calendar,
        .fa-user {
            margin-right: 10px;
        }

        .button-container {
            display: flex;
            justify-content: space-between;
        }

        .main-button {
            width: 45%;
            flex-grow: 1;
            height: 600px;
            padding: 20px;
            background-color: #16a085; /* Change this color to the desired one */
            color: #fff;
            text-align: center;
            text-decoration: none;
            font-size: 100px;
            border-radius: 15px;
            margin: 0 5px; /* Adjust the margin between buttons */
            transition: background-color 0.3s ease;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .main-button:hover {
            background-color: #12876f; /* Change this color to the desired hover color */
        }

        body {
            background: #1abc9c;
            overflow: hidden;
        }

        .fa-calendar,
        .fa-user {
            margin-right: 10px;
        }
    .navigation {
            position: absolute;
            top: 20px;
            left: 20px;
            z-index: 1;
        }

        .navigation a {
            margin-right: 20px;
        }
    </style>
</head>
<body>

<!-- Navigation buttons -->


<div class="container">
    <div class="wrapper">
        <div class="title"><span></span></div>
        <div class="button-container">
            <a href="{{ url_for('views.booking') }}" class="main-button left">Booking <i
                    class="fas fa-calendar"></i></a>
            <a href="{{ url_for('views.profile') }}" class="main-button right">Profile <i class="fas fa-user"></i></a>
        </div>
    </div>
</div>
</body>
</html>

app/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');

        body {
            background: #1abc9c;
            font-family: 'Poppins', sans-serif;
            overflow: hidden;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        h1 {
            color: #fff;
            text-align: center;
            margin-bottom: 20px;
        }

        div {
            background: #fff;
            border-radius: 5px;
            box-shadow: 0px 4px 10px 1px rgba(0, 0, 0, 0.1);
            margin: 10px;
            padding: 20px;
            width: 300px;
            text-align: center;
        }

        p {
            color: #333;
            font-size: 16px;
            margin-bottom: 15px;
        }

        strong {
            font-weight: bold;
        }

        h2 {
            color: #16a085;
            font-size: 24px;
            margin-bottom: 10px;
        }

        ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
            max-height: 200px; /* Ограничение высоты для скролла */
            overflow-y: auto; /* Включение вертикального скролла при превышении высоты */
            text-align: center;
        }

        li {
            background: #fff;
            border-radius: 5px;
            box-shadow: 0px 4px 10px 1px rgba(0, 0, 0, 0.1);
            margin: 10px;
            padding: 20px;
            width: 250px;
        }

        form {
            margin-top: 20px;
        }

        button {
            background: #16a085;
            color: #fff;
            padding: 8px 16px;
            border-radius: 5px;
            font-weight: bold;
            cursor: pointer;
            transition: background 0.3s ease;
        }

        button:hover {
            background: #12876f;
        }
    </style>
</head>
<body>



<h1>User Profile</h1>

<div>
    <p><strong>Name:</strong> {{ current_user.username }}</p>
    <p><strong>Email:</strong> {{ current_user.email }}</p>
    <p><strong>Password:</strong> *********</p>

    <h2>Reserved Tables</h2>
    {% if current_user.reservations %}
        <ul>
            {% for reservation in current_user.reservations %}
                <li>
                    <strong>Restaurant:</strong> {{ reservation.table.restaurant.name }}<br>
                    <strong>Table Number:</strong> {{ reservation.table.table_number }}<br>
                    <strong>Reservation Time:</strong> {{ reservation.reservation_time.strftime('%Y-%m-%d %H:%M') }}<br>
                    <form action="{{ url_for('views.cancel_reservation', reservation_id=reservation.reservation_id) }}" method="post">
                        <button type="submit">Cancel Reservation</button>
                    </form>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No reservations yet.</p>
    {% endif %}

    <form action="{{ url_for('views.logout') }}" method="post">
        <button type="submit">Logout</button>
    </form>
</div>

</body>
</html>

app/templates/restaurant.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ restaurant.name }} Details</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');

        body {
            background: #1abc9c;
            font-family: 'Poppins', sans-serif;
            overflow: hidden;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        h1 {
            color: #fff;
            text-align: center;
            margin-bottom: 20px;
        }

        div {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h2 {
            color: #16a085;
            font-size: 24px;
            margin-bottom: 10px;
        }

        p {
            color: #777;
            font-size: 14px;
            margin-bottom: 10px;
        }

        form {
            margin-top: 10px;
            text-align: center;
        }

        label {
            color: #fff;
            margin-right: 5px;
        }

        textarea {
            width: 100%;
            padding: 8px;
            border-radius: 5px;
            border: 1px solid #ccc;
            margin-bottom: 10px;
        }

        input[type="submit"] {
            background: #16a085;
            color: #fff;
            padding: 8px 16px;
            border-radius: 5px;
            font-weight: bold;
            transition: background 0.3s ease;
        }

        input[type="submit"]:hover {
            background: #12876f;
        }

        ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
            max-height: 400px; /* Ограничение высоты для скролла */
            overflow-y: auto; /* Включение вертикального скролла при превышении высоты */
            text-align: center;
        }

        li {
            background: #fff;
            border-radius: 5px;
            box-shadow: 0px 4px 10px 1px rgba(0, 0, 0, 0.1);
            margin: 10px;
            padding: 20px;
            width: 300px;
        }

        h3 {
            color: #333;
            font-size: 18px;
            margin-bottom: 10px;
        }

        span {
            color: #777;
            font-size: 14px;
        }

        a {
            text-decoration: none;
            background: #16a085;
            color: #fff;
            padding: 8px 16px;
            border-radius: 5px;
            font-weight: bold;
            transition: background 0.3s ease;
        }

        a:hover {
            background: #12876f;
        }
    </style>
</head>
<body>

    <h1>{{ restaurant.name }} Details</h1>

    <div>
        <h2>{{ restaurant.name }}</h2>
        <p>{{ restaurant.address }}</p>
        <h3>{{ restaurant.description }}</h3>

        <form action="{{ url_for('views.select_time', restaurant_id=restaurant.restaurant_id) }}" method="get">
            <label for="table">Select a Table:</label>
            <select id="table" name="table">
                {% for table in restaurant.tables %}
                    {% if not table.is_booked %}
                        <option value="{{ table.table_id }}">Table {{ table.table_number }}</option>
                    {% endif %}
                {% endfor %}
            </select>

            <input type="submit" value="Continue to Time Selection">
        </form>

        <h2>Comments</h2>
        <ul>
            {% for comment in restaurant.comments %}
                <li>
                    <h3>{{ comment.user.username }}</h3>
                    <p>{{ comment.comment_text }}</p>
                    <span>Rating: {{ comment.rating }}/5</span>
                </li>
            {% endfor %}
        </ul>

        <form action="{{ url_for('views.add_comment', restaurant_id=restaurant.restaurant_id) }}" method="post">
            <label for="comment_text">Add a Comment:</label>
            <textarea id="comment_text" name="comment_text" rows="4" required></textarea>

            <label for="rating">Rating:</label>
            <select id="rating" name="rating" required>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>

            <input type="submit" value="Add Comment">
        </form>
    </div>
</body>
</html>

app/templates/select_time.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Choose Reservation Time</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');

        body {
            background: #1abc9c;
            font-family: 'Poppins', sans-serif;
            overflow: hidden;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        h1 {
            color: #fff;
            text-align: center;
            margin-bottom: 20px;
        }

        div {
            background: #fff;
            border-radius: 5px;
            box-shadow: 0px 4px 10px 1px rgba(0, 0, 0, 0.1);
            margin: 10px;
            padding: 20px;
            width: 300px;
            text-align: center;
        }

        h2 {
            color: #16a085;
            font-size: 24px;
            margin-bottom: 10px;
        }

        p {
            color: #333;
            font-size: 16px;
            margin-bottom: 15px;
        }

        form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        label {
            display: block;
            margin-bottom: 10px;
            color: #333;
        }

        input {
            width: calc(100% - 20px); /* Учтем внутренние отступы в 10px по бокам */
            padding: 8px;
            border-radius: 5px;
            border: 1px solid #ccc;
            margin: 0 0 15px 0;
            box-sizing: border-box; /* Учтем внутренние отступы в расчете ширины */
        }

        input[type="submit"] {
            background: #16a085;
            color: #fff;
            padding: 8px 16px;
            border-radius: 5px;
            font-weight: bold;
            cursor: pointer;
            transition: background 0.3s ease;
        }

        input[type="submit"]:hover {
            background: #12876f;
        }
    </style>
</head>
<body>


<h1>Choose Reservation Time</h1>

<div>
    <h2>{{ restaurant.name }}</h2>
    <p>Selected Table: Table {{ selected_table_number }}</p>

    <form action="{{ url_for('views.confirm_booking', restaurant_id=restaurant_id, table_id=selected_table_id) }}" method="post">
        <label for="date">Select Date:</label>
        <input type="date" id="date" name="date" required>

        <label for="time">Select Time:</label>
        <input type="time" id="time" name="time" required>

        <input type="submit" value="Book Table">
    </form>
</div>

</body>
</html>